services:
  rag-service:
    build: ./backend # Build context is the backend folder
    ports:
      - "8000:8080"
      - "11434:11434"
    
    # --- Forces a working DNS to fix network timeouts ---
    dns:
      - 8.8.8.8
      - 1.1.1.1

    volumes:
      - ollama_models:/root/.ollama
      - ./local_chroma_db:/app/local_chroma_db
    environment:
      - OLLAMA_BASE_URL=http://localhost:11434

volumes:
  ollama_models: